version: '3.8'

services:
  bookingdetail:
    build:
      context: ./bookingdetail
    ports:
      - "3001:3000"  # Map host port 3001 to container port 3000

  bookinghistory:
    build:
      context: ./bookinghistory
    ports:
      - "3002:3000"  # Map host port 3002 to container port 3000
  
  confirmbooking:
    build:
      context: ./confirmbooking
    ports:
      - "3003:3000"  # Map host port 3003 to container port 3000

  home:
    build:
      context: ./home
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    
  list:
    build:
      context: ./list
    ports:
      - "3004:3000"  # Map host port 3004 to container port 3000
    
  login:
    build:
      context: ./login
    ports:
      - "3005:3000"  # Map host port 3005 to container port 3000
    
  # monolith:
  #   build:
  #     context: ./monolith
  #   ports:
  #     - "3006:3000"  # Map host port 3006 to container port 3000
    
  payment:
    build:
      context: ./payment
    ports:
      - "3007:3000"  # Map host port 3007 to container port 3000
  
  register:
    build:
      context: ./register
    ports:
      - "3008:3000"  # Map host port 3008 to container port 3000
  
  restaurantdetail:
    build:
      context: ./retaurantdetail
    ports:
      - "3009:3000"  # Map host port 3009 to container port 3000

  shell:
    build:
      context: ./shell
    ports:
      - "3010:3000"  # Map host port 3010 to container port 3000
